### ISSUE TITLE
Fetching Data In React: The API used in this lesson no longer works.

### ISSUE THREAD

**Issue by ctcleary** [TheOdinProject/curriculum#29438]
### Checks

- [x] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I just wanted to notify the project folks that the API used in the React Fetch lesson does not appear to work. It's not a dire issue, since it's still possible to follow most of the lesson, but it felt worth reporting.

The API URL that the lesson tries to fetch is <https://jsonplaceholder.typicode.com/photos>

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react

**Comment by MaoShizhong** [comment]
Just a heads up that it's because [via.placeholder.com got bought and taken down](https://github.com/typicode/jsonplaceholder/issues/209) but there is a [PR to replace jsonplaceholder's images](https://github.com/typicode/jsonplaceholder/pull/210) that the API owner is aware of though yet to review, so that'll hopefully get resolved in due time.

**Comment by bigacz** [comment]
This API still isn't working. I think it would be a good idea to replace it with https://picsum.photos/ specifically https://picsum.photos/v2/list. Not sure if the authors of this API should be contacted in some way, they have an MIT license in the github repo, but does that mean that it can be used in the curriculum freely?

**Comment by CouchofTomato** [comment]
@TheOdinProject/react Can someone take a look at this please.

**Comment by wise-king-sullyman** [comment]
Replacing it with picsum seems like a good idea to me!

I'm sure it would be fine, but I'll reach out to the creator of that API first just in case, since I'm not sure if we might increase traffic going to it a good bit. I will update this issue after I've heard back from them.

**Comment by wise-king-sullyman** [comment]
I heard back from the creator of that API! He is fine with us using it, but did have one request: 

> If possible, to identify your traffic depending on how the API is consumed, either setting a User Agent, or not blocking the Referrer header is appreciated

For which we should probably just add a note in the lesson I think, but I'm open to other ideas.

@bigacz is this something that you were interested in working on, or did you just want to suggest that API?

**Comment by bigacz** [comment]
Yes, I am interested in solving this issue.

I am not sure how exactly the creator of the API wants to identify traffic. Does he want to differentiate people doing TOP from the others, or just to differentiate personal projects in general from commercial and other uses?

I ask this because if it is the former, then how will not blocking the referrer header help him identify who is from TOP and who is not? Not blocking it in codesandbox will work, but I think more people are setting up this exercise locally, and I think he isn't aware of that. In that case the referrer info won't be helpful to him, and we would have to instruct people to add user agent header, which I think is a worse option, as there will be more people that don't include it, than people that block the referrer header.

If it is the latter, I think not blocking the referrer will be perfectly fine.

**Comment by wise-king-sullyman** [comment]
I would assume the former, and while I agree that not everyone will include it, I think if we show how to do it, most people will follow the approach we show.

Thanks for volunteering to work on this!

**Comment by mao-sz** [comment]
@bigacz is this something you still wish to work on?

**Comment by ToastedGMS** [comment]
I understand this issue is assigned but if eventually available I'd like to help with it.

**Comment by bigacz** [comment]
Sorry, I won't be able to make a PR for this issue, feel free to assign it to someone else.

**Comment by mao-sz** [comment]
@ToastedGMS all yours
